### ISSUE TITLE
Can't Login / No Reset Password

### ISSUE THREAD

**Issue by j-a-mercury-nj** [TomaQ/KaniWani#13]
I'm currently locked out and can't remember or reset my password. Thanks for any help!

**Comment by TomaQ** [comment]
I currently don't have a reset password method implemented. You'll have to delete and recreate the database. Run these commands in your terminal in the folder the project is in: 
rake db:reset
rake db:migrate

The project currently doesn't save progress right now so the only think that's important on the account is your wanikani api key. You can also just make a new user if you want with the same api key.

**Comment by TomaQ** [comment]
I just realized this but do you mean the site kaniwani.com? I don't run that site actually sorry.

**Comment by j-a-mercury-nj** [comment]
I did mean the site. I couldn't find any contact info and though it might be the same person. Oh well!
-Jeremy
